### ISSUE TITLE
Posty okolicznościowe/ŚWIĘTA

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/SocialMedia#18]
- Boże Narodzenie
- Nowy Rok
- Wielkanoc
- Walentynki
- Dzień Dziecka
- Dzień Chłopca
- Dzień Kobiet
- dodać przypominajkę

**Comment by monikakrawczak** [comment]
#12

**Comment by MargoWM** [comment]
Przypominajka dodana na slack
