### ISSUE TITLE
Ulotka dla nowych wolontariuszy

### ISSUE THREAD

**Issue by MargoWM** [CodeForPoznan/SocialMedia#5]
Należy przygotować ulotkę z krótką informacją dotyczącą CfP oraz tego czym się zajmujemy. Ma ona na celu wsparcie nowych wolontariuszy w pierwszych krokach w CfP.

**Comment by magul** [comment]
Ustaliliśmy (na chwilę obecną), że informacje o używanych technologiach do slajdów i jednocześnie nie mamy zasobów ludzkich, żeby utrzymywać kolejne miejsce, w którym musielibyśmy aktualizować takie informacje.
